## Configuración de Spring
spring:
    application:
        name: ms-books-catalogue

    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3310/books_catalogue_db}
        driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

## Configuración de instancia
server:
    port: ${PORT:8790}

## Configuración del cliente Eureka
eureka:
    client:
        enabled: false
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
        hostname: ms-books-catalogue
